var stimuliData = [
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_01",
    "Clip ID": "M1_01",
    "Duration (s)": "1.480896",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "5.043558001",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "You kind of get spoiled."
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_02",
    "Clip ID": "M1_02",
    "Duration (s)": "1.508312",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "4.539559014",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "It's a really nice place to live."
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_04",
    "Clip ID": "M1_03",
    "Duration (s)": "1.220375",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "5.087881591",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "Being in medical field."
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_06",
    "Clip ID": "M1_04",
    "Duration (s)": "0.999906",
    "# of IPs": "1",
    "# of words": "2",
    "Speech rate (words per s)": "2.000188035",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "Parallel ways."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_04",
    "Clip ID": "M2_01",
    "Duration (s)": "3.0",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "2.667",
    "Link": "https://youtu.be/zRZu05R_eD8?t=402",
    "Transcription": "The airport is basically a one-story building."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_05",
    "Clip ID": "M2_02",
    "Duration (s)": "1.039885",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "3.846",
    "Link": "https://youtu.be/zRZu05R_eD8?t=550",
    "Transcription": "So that was great."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_06",
    "Clip ID": "M2_03",
    "Duration (s)": "0.928833",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "5.382",
    "Link": "https://youtu.be/P5kKKe_-qJ8?t=1138",
    "Transcription": "I just wanted to get up."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_07",
    "Clip ID": "M2_04",
    "Duration (s)": "2.180729",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.751",
    "Link": "https://youtu.be/P5kKKe_-qJ8?t=1826",
    "Transcription": "People just focus on making money."
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_02",
    "Clip ID": "M3_01",
    "Duration (s)": "1.659469",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "2.411",
    "Link": "",
    "Transcription": "To further my education."
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_03",
    "Clip ID": "M3_02",
    "Duration (s)": "1.70975",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.924",
    "Link": "",
    "Transcription": "And then on Sunday morning"
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_04",
    "Clip ID": "M3_03",
    "Duration (s)": "1.483458",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.371",
    "Link": "",
    "Transcription": "Not too far away from here."
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_08",
    "Clip ID": "M3_04",
    "Duration (s)": "2.564635",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "3.508",
    "Link": "",
    "Transcription": "They have to learn about what they're talking about."
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_07",
    "Clip ID": "M4_01",
    "Duration (s)": "2.112052",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.841",
    "Link": "",
    "Transcription": "The main source is from class."
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_08",
    "Clip ID": "M4_02",
    "Duration (s)": "1.785187",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "3.361",
    "Link": "",
    "Transcription": "I'm still struggling to be honest."
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_09",
    "Clip ID": "M4_03",
    "Duration (s)": "2.137188",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "1.872",
    "Link": "",
    "Transcription": "They didn't really respond."
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_10",
    "Clip ID": "M4_04",
    "Duration (s)": "2.538281",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.364",
    "Link": "",
    "Transcription": "The most intimate group of friends."
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_02",
    "Clip ID": "M5_01",
    "Duration (s)": "2.002865",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.994",
    "Link": "https://youtu.be/1CFCXDiJH5g?t=287",
    "Transcription": "All of us were very young, so..."
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_06",
    "Clip ID": "M5_02",
    "Duration (s)": "1.560854",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.204",
    "Link": "",
    "Transcription": "In December, it was cold."
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_07",
    "Clip ID": "M5_03",
    "Duration (s)": "1.118844",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "3.576",
    "Link": "",
    "Transcription": "I said, what is this?"
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_08",
    "Clip ID": "M5_04",
    "Duration (s)": "2.679688",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "2.612",
    "Link": "",
    "Transcription": "We have a very enjoyable life, nothing."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_01",
    "Clip ID": "F1_01",
    "Duration (s)": "2.72926",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "1.832",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2308",
    "Transcription": "Because of the limited space."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_02",
    "Clip ID": "F1_02",
    "Duration (s)": "2.456333",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.442",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2371",
    "Transcription": "I end up going to high school."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_06",
    "Clip ID": "F1_03",
    "Duration (s)": "2.034542",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.440",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2308",
    "Transcription": "No, actually I was the only one."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_07",
    "Clip ID": "F1_04",
    "Duration (s)": "3.175875",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "3.149",
    "Link": "",
    "Transcription": "But majority of the time people offered to pick me up."
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_03",
    "Clip ID": "F2_01",
    "Duration (s)": "3.200677",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "1.250",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1326",
    "Transcription": "It's head-to-tail restaurant."
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_07",
    "Clip ID": "F2_02",
    "Duration (s)": "2.902938",
    "# of IPs": "1",
    "# of words": "12",
    "Speech rate (words per s)": "4.134",
    "Link": "",
    "Transcription": "They buy a whole pig and then they eat their way through it."
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_09",
    "Clip ID": "F2_03",
    "Duration (s)": "1.372927",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "5.098",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "And they charge lots and lots of money."
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_11",
    "Clip ID": "F2_04",
    "Duration (s)": "4.716052",
    "# of IPs": "1",
    "# of words": "11",
    "Speech rate (words per s)": "2.332",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "And then upstairs in her apartment, she would make rice wine."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_09",
    "Clip ID": "F3_01",
    "Duration (s)": "4.267563",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "1.875",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "My parents, my two sisters, and my two brothers."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_11",
    "Clip ID": "F3_02",
    "Duration (s)": "4.438833",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "2.253",
    "Link": "",
    "Transcription": "So it wasn't residential on both sides of the street..."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_12",
    "Clip ID": "F3_03",
    "Duration (s)": "1.738271",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.877",
    "Link": "",
    "Transcription": "At least one family had moved."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_13",
    "Clip ID": "F3_04",
    "Duration (s)": "1.651802",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "4.843",
    "Link": "",
    "Transcription": "There were a lot of children in the area."
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_03",
    "Clip ID": "F4_01",
    "Duration (s)": "1.835479",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.724",
    "Link": "",
    "Transcription": "Probably right before I turn six."
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_04",
    "Clip ID": "F4_02",
    "Duration (s)": "2.916635",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.058",
    "Link": "",
    "Transcription": "Yeah, a little bit, like elementary school."
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_05",
    "Clip ID": "F4_03",
    "Duration (s)": "3.670938",
    "# of IPs": "1",
    "# of words": "12",
    "Speech rate (words per s)": "3.269",
    "Link": "",
    "Transcription": "Yeah, it was an apartment building. It was like a one-bedroom"
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_06",
    "Clip ID": "F4_04",
    "Duration (s)": "1.514",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.303",
    "Link": "",
    "Transcription": "It was hard for my mom."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_06",
    "Clip ID": "F5_01",
    "Duration (s)": "1.144573",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "3.495",
    "Link": "https://youtu.be/aFLgw8VpkPw?t=849",
    "Transcription": "He worked very hard."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_07",
    "Clip ID": "F5_02",
    "Duration (s)": "2.006958",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.491",
    "Link": "https://youtu.be/aFLgw8VpkPw?t=849",
    "Transcription": "We sort of like stay together."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_08",
    "Clip ID": "F5_03",
    "Duration (s)": "3.162094",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "2.530",
    "Link": "",
    "Transcription": "It was a totally new experience to me."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_09",
    "Clip ID": "F5_04",
    "Duration (s)": "0.83549",
    "# of IPs": "1",
    "# of words": "3",
    "Speech rate (words per s)": "3.592",
    "Link": "",
    "Transcription": "Oh my god."
  }
];