var stimuliData = [
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_01",
    "Clip ID": "M1_01",
    "Duration (s)": "1.220375",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "4.095",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "being in the medical field,"
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_02",
    "Clip ID": "M1_02",
    "Duration (s)": "0.999906",
    "# of IPs": "1",
    "# of words": "2",
    "Speech rate (words per s)": "2.000",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "parallel ways."
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_04",
    "Clip ID": "M1_03",
    "Duration (s)": "1.480896",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "2.701",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "you kind of get spoiled."
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_06",
    "Clip ID": "M1_04",
    "Duration (s)": "1.508312",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "4.640",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "It's a really nice place to live."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_04",
    "Clip ID": "M2_01",
    "Duration (s)": "1.025729",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "3.900",
    "Link": "https://youtu.be/zRZu05R_eD8?t=402",
    "Transcription": "being in the squallor."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_05",
    "Clip ID": "M2_02",
    "Duration (s)": "2.665333",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "3.001",
    "Link": "https://youtu.be/zRZu05R_eD8?t=550",
    "Transcription": "But later on, when I traveled quite a bit,"
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_06",
    "Clip ID": "M2_03",
    "Duration (s)": "3.026990",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "2.643",
    "Link": "https://youtu.be/P5kKKe_-qJ8?t=1138",
    "Transcription": "The airport is basically a one-story building."
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_07",
    "Clip ID": "M2_04",
    "Duration (s)": "2.180729",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.751",
    "Link": "https://youtu.be/P5kKKe_-qJ8?t=1826",
    "Transcription": "People just focus on making money."
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_02",
    "Clip ID": "M3_01",
    "Duration (s)": "1.659469",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "2.411",
    "Link": "",
    "Transcription": "to further my education."
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_03",
    "Clip ID": "M3_02",
    "Duration (s)": "1.709750",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.924",
    "Link": "",
    "Transcription": "And then on Sunday morning"
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_04",
    "Clip ID": "M3_03",
    "Duration (s)": "3.378094",
    "# of IPs": "1",
    "# of words": "12",
    "Speech rate (words per s)": "3.553",
    "Link": "",
    "Transcription": "Probably you heard on the radio or on the news, they are downsizing."
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_08",
    "Clip ID": "M3_04",
    "Duration (s)": "2.564635",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "3.508",
    "Link": "",
    "Transcription": "You had to learn about what they're talking about."
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_07",
    "Clip ID": "M4_01",
    "Duration (s)": "0.883969",
    "# of IPs": "1",
    "# of words": "3",
    "Speech rate (words per s)": "3.393",
    "Link": "",
    "Transcription": "yeah last fall"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_08",
    "Clip ID": "M4_02",
    "Duration (s)": "2.538281",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.364",
    "Link": "",
    "Transcription": "the most intimate group of friends,"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_09",
    "Clip ID": "M4_03",
    "Duration (s)": "2.137188",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "1.872",
    "Link": "",
    "Transcription": "they didn't really respond"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_10",
    "Clip ID": "M4_04",
    "Duration (s)": "1.785187",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "3.361",
    "Link": "",
    "Transcription": "I'm still struggling to be honest."
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_02",
    "Clip ID": "M5_01",
    "Duration (s)": "1.863625",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.755",
    "Link": "https://youtu.be/1CFCXDiJH5g?t=287",
    "Transcription": "half an hour, probably fourty five minutes away."
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_06",
    "Clip ID": "M5_02",
    "Duration (s)": "2.229229",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.244",
    "Link": "",
    "Transcription": "Because back in the seventies,"
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_07",
    "Clip ID": "M5_03",
    "Duration (s)": "4.375990",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "1.829",
    "Link": "",
    "Transcription": "So we start transporting, moving kids outside of the neighborhood."
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_08",
    "Clip ID": "M5_04",
    "Duration (s)": "1.560854",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.204",
    "Link": "",
    "Transcription": "and the summer was cold."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_01",
    "Clip ID": "F1_01",
    "Duration (s)": "2.729260",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "1.832",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2308",
    "Transcription": "because of the limited space."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_02",
    "Clip ID": "F1_02",
    "Duration (s)": "2.286385",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.187",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2371",
    "Transcription": "clothes or fashion for that matter."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_06",
    "Clip ID": "F1_03",
    "Duration (s)": "2.456333",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.442",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2308",
    "Transcription": "I end up going to high school."
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_07",
    "Clip ID": "F1_04",
    "Duration (s)": "3.175875",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "3.149",
    "Link": "",
    "Transcription": "but majority of the time people offer to pick me up."
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_03",
    "Clip ID": "F2_01",
    "Duration (s)": "1.654760",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.021",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1326",
    "Transcription": "and then upstairs in her apartment,"
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_07",
    "Clip ID": "F2_02",
    "Duration (s)": "1.902969",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.627",
    "Link": "",
    "Transcription": "And so my mother also"
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_09",
    "Clip ID": "F2_03",
    "Duration (s)": "2.078781",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "4.811",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "But it was illegal at that time, and I didn't know that."
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_07",
    "Clip ID": "F2_04",
    "Duration (s)": "2.902938",
    "# of IPs": "1",
    "# of words": "12",
    "Speech rate (words per s)": "4.134",
    "Link": "",
    "Transcription": "They buy a whole pig and then they eat their way through it."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_09",
    "Clip ID": "F3_01",
    "Duration (s)": "4.267563",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "1.875",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "my parents, my two sisters, and my two brothers."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_11",
    "Clip ID": "F3_02",
    "Duration (s)": "1.165760",
    "# of IPs": "1",
    "# of words": "3",
    "Speech rate (words per s)": "2.574",
    "Link": "",
    "Transcription": "as homeless people."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_12",
    "Clip ID": "F3_03",
    "Duration (s)": "2.959219",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.028",
    "Link": "",
    "Transcription": "So initially my father said no."
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_13",
    "Clip ID": "F3_04",
    "Duration (s)": "4.115500",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "2.430",
    "Link": "",
    "Transcription": "they would also know just because it's easier to identify families."
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_03",
    "Clip ID": "F4_01",
    "Duration (s)": "1.835479",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "2.724",
    "Link": "",
    "Transcription": "Probably right before I turned six."
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_04",
    "Clip ID": "F4_02",
    "Duration (s)": "2.916635",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.058",
    "Link": "",
    "Transcription": "Yeah, a little bit, like elementary school."
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_05",
    "Clip ID": "F4_03",
    "Duration (s)": "3.670938",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "2.724",
    "Link": "",
    "Transcription": "Yeah, it was an apartment building. It was like a one-bedroom"
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_06",
    "Clip ID": "F4_04",
    "Duration (s)": "3.988719",
    "# of IPs": "1",
    "# of words": "14",
    "Speech rate (words per s)": "3.509",
    "Link": "",
    "Transcription": "So when I got in, I knew that I can take the train, it was easy to commute."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_06",
    "Clip ID": "F5_01",
    "Duration (s)": "0.835490",
    "# of IPs": "1",
    "# of words": "3",
    "Speech rate (words per s)": "3.592",
    "Link": "https://youtu.be/aFLgw8VpkPw?t=849",
    "Transcription": "Oh my god."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_07",
    "Clip ID": "F5_02",
    "Duration (s)": "1.750198",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "2.286",
    "Link": "https://youtu.be/aFLgw8VpkPw?t=849",
    "Transcription": "My father also, you know,"
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_08",
    "Clip ID": "F5_03",
    "Duration (s)": "3.162094",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "2.530",
    "Link": "",
    "Transcription": "It was a totally new experience to me."
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_09",
    "Clip ID": "F5_04",
    "Duration (s)": "3.404396",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "2.056",
    "Link": "",
    "Transcription": "After half a year, I start full-time."
  }
];